from . import main_menu
from . import vpn
from . import proxy
from . import admin
from . import admin_stats
from . import admin_commands
from . import admin_users
from . import admin_backup
from . import admin_news
from . import extend
from . import vpn_admin
from . import errors
